# Generated by Django 4.2.4 on 2023-09-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB1', '0002_userprofile_remove_collegeday_student_class_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='WEB1.course'),
        ),
    ]
