# Generated by Django 4.2.4 on 2023-10-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB1', '0003_remove_course_student_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='myclass',
            field=models.ManyToManyField(related_name='myclass', to='WEB1.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(related_name='student', to='WEB1.student'),
        ),
    ]
